### ISSUE TITLE
Issue removing integration via HACS repository 

### ISSUE THREAD

**Issue by olylak** [eavanvalkenburg/sia#48]
As a component now is an official one I'm trying to remove it from HACS and install it using HA integrations.
But uninstalling the the integration via HACS fails: 

After I unistall it and restart HA component is still in the list of installed ones and asking for upgrade.

<img width="575" alt="2021-06-04 21_22_46-Community - Home Assistant" src="https://user-images.githubusercontent.com/3715218/120846622-1346fa00-c57b-11eb-8eef-e8c83c7cc0a5.png">

**Comment by eavanvalkenburg** [comment]
That is strange, probably check if your custom component folder is empty...

**Comment by eavanvalkenburg** [comment]
And make sure to delete for integration before removing the HACS version since the config is slightly different

**Comment by olylak** [comment]
Deleted integration before deleting component from the HACS. That's really strange. Did it already several times...not sure what I'm doing wrong. After restart it's still there

**Comment by eavanvalkenburg** [comment]
And did you check the actual folder?

**Comment by olylak** [comment]
2021-06-04 21:18:38 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-06-04 21:18:51 ERROR (MainThread) [custom_components.hacs] <Integration hacs/integration> Could not read manifest.json [encoding without a string argument]
2021-06-04 21:18:57 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 140, in startup_tasks
    await self.handle_critical_repositories()
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 195, in handle_critical_repositories
    critical = json.loads(critical.content)
AttributeError: 'list' object has no attribute 'content'
2021-06-04 21:28:41 ERROR (MainThread) [custom_components.hacs] <Integration eavanvalkenburg/sia> Could not read manifest.json [encoding without a string argument]
2021-06-04 21:29:25 ERROR (MainThread) [frontend.js.latest.202106030] https://.../frontend_latest/chunk.820b4f10c06bebb7d0bb.js:179:939 Uncaught TypeError: Cannot read property 'attributes' of undefined
2021-06-04 21:30:11 ERROR (MainThread) [frontend.js.latest.202106030] https://.../frontend_latest/chunk.820b4f10c06bebb7d0bb.js:179:939 Uncaught TypeError: Cannot read property 'attributes' of undefined

**Comment by olylak** [comment]
> And did you check the actual folder?

You mean custome_components?

Nothing except HACS 

<img width="193" alt="2021-06-04 21_35_24-custom_components" src="https://user-images.githubusercontent.com/3715218/120847951-dc71e380-c57c-11eb-91d2-8602ad05906e.png">

**Comment by eavanvalkenburg** [comment]
Yeah please check if someone on the HACS side knows what this might be

**Comment by eavanvalkenburg** [comment]
Or maybe you can just ignore it and install using the new config flow, you can check if you then also get configuration options them you know it's the official one
